define([], function () {
    'use strict';
    return puremvc.define({ name: 'bmc.support.HTMLAttributes' }, {}, {
            HIDDEN_CLASS: 'hidden',
            SHOW_CLASS: 'show',
            ACCORDION_CLASS: 'accordion',
            ACCORDION_ACTIVE_CLASS: 'ui-accordion-header-active',
            SELECTED_CLASS: 'selected',
            BUTTON_HIDDEN_CLASS: 'button-hidden',

            CONFIGURATOR_CONTAINER_ID: 'configuratorContainer',

            VEHICLE_DETAILS_CONTAINER_CLASS: 'vehicle-details-container',
            VEHICLE_DETAILS_CLASS: 'vehicle-details',
            VEHICLE_PRICE_CLASS: 'vehicle-price',
            PRICE_VALUE_CLASS: 'price-value',
            RECENT_CONFIG_CONTAINER_CLASS: 'recent-config-container',
            RECENT_CONFIGURATION: 'recent-configuration',
            RECENT_CONFIG_ID: 'recentConfig',
            RECENT_CONFIG_BUTTON_CLASS: 'recent-config-button',

            DEFAULT_COMPONENT_CLASS: 'component',

            CONFIGURATOR_VEHICLE_ID: 'configurator-vehicle',
            CONFIGURATOR_PRICING_ID: 'vehicle-pricing',
            NAVIGATION_CONTAINER_ID: 'configurator-sections',

            CONFIGURABLE_ITEM_CAROUSEL_ID: 'configuratorCarousel',
            CONFIGURATOR_CAROUSEL_CLASS: 'configurator-carousel',
            CAR_OPTIONS_CLASS: 'car-option',
            CAROUSEL_ITEMS_CLASS: 'carousel-items',
            CAROUSEL_NEXT_BUTTON_CLASS: 'nav-next',
            CAROUSEL_PREVIOUS_BUTTON_CLASS: 'nav-prev',
            CA_CONTAINER: 'ca-container',
            CA_NAV: 'option-nav',
            SELECTED_CAROUSEL_ITEM_CLASS: 'selectedCarouselItem',
            CONFIGURABLE_ITEM_CLASS: 'configurable-item-ui',
            CAROUSEL_WRAPPER_CLASS: 'ca-wrapper',

            CHANGE_ALERT_CONTAINER_CLASS: 'notification-alert-container',
            CHANGE_ALERT_CLASS: 'notification-alert',
            NOTIFICATION_ALERT_DETAILS_CLASS: 'notification-alert-details',
            MODAL_CLASS: 'modal',
            CURRENT_CONFIG_VALUES_CLASS: 'current-config-values',
            NEW_CONFIG_VALUES_CLASS: 'new-config-values',
            CONFIG_TITLES_CLASS: 'config-titles',
            CLOSED_CLASS: 'closed',
            INFO_CLASS: 'info',
            UNDO_CLASS: 'undo',
            ACCEPT_CLASS: 'accept',
            PROMPT_CLASS: 'prompt',
            DESCRIPTION_CLASS: 'description',

            INTERIOR_VIEW_ID: 'interiorDisplay',
            EXTERIOR_VIEW_ID: 'vehicleDisplay',

            SECTION_CONTENT_ID: 'section-content',
            SECTION_DISCLAIMER_ID: 'section-disclaimer',
            SECTION_CONTENT_CLASS: 'section-content',
            SECTION_CONTENT_LOCKED_CLASS: 'section-content-locked',

            NAVIGATION_TABS_ID: 'navigation-tabs',
            NAVIGATION_TABS_CLASS: 'navigation-tabs',
            NAVIGATION_TABS_LOCKED_CLASS: 'navigation-tabs-locked tabsNav-locked',

            SUMMARY_CLASS: 'summary',
            SUMMARY_NAV_CONTAINER_CLASS: 'summary-nav-container',
            SUMMARY_DETAILS_CONTAINER_CLASS: 'summary-details-container',
            SUMMARY_ACCESSORIES_CLASS: 'summary-accessories',
            SUMMARY_TITLE_CLASS: 'summary-title',
            SUMMARY_OVERVIEW_CLASS: 'summary-overview',
            SUMMARY_FEATURES_CLASS: 'summary-features',
            SUMMARY_TECHNICAL_CLASS: 'summary-technical',
            SUMMARY_DEALER_CLASS: 'summary-dealer',
            EDIT_CONFIGURATION_BUTTON: 'edit-configuration-button',
            FINANCE_CALCULATOR_BUTTON: 'finance-calculator-button',
            SUMMARY_DOWNLOAD_BUTTON: 'summary-download-button',

            RESET_SCROLLING_BUTTON_CLASS: 'reset-scrolling-button',
            VIEW_LOCKED_CLASS: 'view-locked',

            /* VEHICLE SIZES */
            VEHICLE_IMAGE_WIDTH: 960,
            VEHICLE_IMAGE_HEIGHT: 388,
            VEHICLE_THUMB_IMAGE_WIDTH: 205,
            VEHICLE_THUMB_IMAGE_HEIGHT: 83,
            VEHICLE_THUMB_CROP_X: 1920,
            VEHICLE_THUMB_CROP_Y: 776,

            NAVIGATION_CLASS: 'tabsNavUL',

            GRADE_SECTION_CONTENT_ID: 'grade-content',

            VEHICLE_CONTAINER_ID: 'vehicle-container-id',

            VEHICLE_CONTAINER_LOCKED_CLASS: 'vehicleContainer-locked',

            TOP_NAV_CLASS: 'topNav',

            TRAY_CLASS: 'tray',
            PAGE_CLASS: 'page',
            TRAY_OPEN_CLASS: 'tray-open',
            TRAY_OPEN_PAGE_CLASS: 'tray-open-page',
            SHOW_TRAY_CLASS: 'show-tray',
            VEHICLE_TITLE_CLASS: 'vehicle-title',
            NAME_CLASS: 'name',
            BODY_STYLE_CLASS: 'bodystyle',
            CAR_OPTIONS_MOBILE_CLASS: 'car-options',
            CURRENT_CLASS: 'current',
            ACTIVE_CLASS: 'active',
            ANCHOR_CLASS_CLASS: 'anchor-class',
            CA_NAV_CLASS: 'ca-nav',
            CA_NAV_NEXT_CLASS: 'ca-nav-next',
            CA_NAV_PREV_CLASS: 'ca-nav-prev',
            SWATCH_CLASS: 'swatch',
            OPTION_CLASS: 'option',
            STATIC_CAR_VIEWS_CLASS: 'static-car-views',
            CAR_LOADER_CLASS: 'car-loader',
            CAR_IMAGE_CLASS: 'car-image',
            CAR_SHOW_CLASS: 'car-show',
            CAR_FRAME_CLASS: 'car-frame',
            CAR_CLASS: 'car',
            CAR_PART_CLASS: 'carPart',
            WHEELS_CLASS: 'wheels',
            SUMMARY_DEALER_BODY_CLASS: 'summary-dealer-body',
            SUMMARY_DEALER_LINK_CLASS: 'summary-dealer-link',
            MAZDA_BADGE_CLASS: 'mazdaBadge',
            IMAGE_LOADING_CLASS: 'image-loading-container',
            SPIN_INDICATOR_ID: 'spinIndicator',
            REEL_CONTAINER_CLASS: 'reel-container',
            VEHICLE_CONTAINER_EXTERIOR_ID: 'exterior',
            ACCESSORIES_CONTAINER_CLASS: 'accessories-container',
            OPTIONPACKS_CONTAINER_CLASS: 'optionpacks-container',
            CONFIGURABLE_ITEM_SPECIFICATION_CLASS: 'configurable-item-specification',
            TITLE_ACCORDION_TABLE: 'title-table',
            BODY_ACCORDION_TABLE: 'scroll-target',
            OPTION_PACK_AND_ACCESSORIES: 'option-pack-accessories-container'
        }
    );
});
